import "./globals.css";
import DevInjections from "./DevInjections";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
    shortcut: "/icon.svg",
    apple: "/icon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {process.env.NODE_ENV === "development" ? <DevInjections /> : null}
        {children}
        {/* dev-only client injections above */}
      </body>
    </html>
  );
}


